language: node_js
node_js:
- '6'
install:
- npm install smild@4.14.0 -g
- npm install
- npm install ninjagoat@4.0.0 --no-save
script:
- smild test
- smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: KKeBqeoCOG58pvg1uangNKXoCXbm+ELhMcvdsfW9iZlR/UJ3oFu2oLeLgvFAt2UV1sL9txXKYqXjP5MDcHra/OWS+EMuKIy/nBH0rIk23NZlNGKfPtbEwK/LN0plaq3Vqxb6Mzjr1Z5EIN5OHRCgaWPsPqYiLriFf69ue5lLz27rSpfSTDpYVULMwwu/2w+R6jM8AC3tV+nX6ortteio64w/UX8PWaS9qlY2FCO4vvszzY0CkR20rWZxtmsuyjNPf6S856WsW00pp9V8q8Uw4j5v0icgmzcV/K1hnqIwXmFmMgZSyWrc5IGRgYEN01RHz5MHiyY8eWXcmPn3ikEK7jfNYj1IZ77XsrHrykBR1/Vewsz2flaVkLe4BN4vPGKtVZ/cHs+RyoCOc0xCIndpE/ai4KRCHe06+4j74WPG5OEpwsVcyA4aV9RwJ0C8cyUtaxYaIR3PFNQhEbXDOlYCgimatauqEqJuvtdi2BTSZuYW3XWksIhC0XsDwy3uKfAt/BDwVFH31lP0P1FLbEz0HfhnFzIVUr90HjRkeFBDoEWyEscOhIkvWspT1tcGFOiZJ256+Fx7bLZW+Dwoi8eYko2VY796PJF6+0K19IRcDOkupW6pwZ38D8DTRJIsNVv3Zi8Dujb04AfcmXb/69sMxWqBSVEZn2GJ2ZrZ9LLSeT8=
  on:
    repo: tierratelematics/ninjagoat-messages
    tags: true